<a href="https://colab.research.google.com/github/pinemoon01/precamp13/blob/master/2016343_%EB%B0%95%EC%A7%80%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.mkdir("grade")   #grade라는 새 폴더 만들기

In [ ]:
in_file = open("./grade/seongjuk.txt", "r")  #grade폴더에 seoung_juk.txt 파일 속하게 한 다음에 파일 열기

In [ ]:
line_all = in_file.read()   #파일 내용 다 불러오기
print(line_all)

홍길동 0.1 74 0.1 79 0.1 72 0.1 69 0.1 81 0.1 75 0.1 73 0.05 70 0.05 75 0.2 80
박문수 0.1 84 0.1 79 0.1 87 0.1 90 0.1 85 0.1 82 0.1 86 0.05 83 0.05 87 0.2 89 
김철수 0.1 66 0.1 63 0.1 89 0.1 65 0.1 57 0.1 70 0.1 64 0.05 67 0.05 65 0.2 62 
이영희 0.1 91 0.1 99 0.1 89 0.1 90 0.1 100 0.1 100 0.1 98 0.05 95 0.05 85 0.2 70


In [ ]:
with open("./grade/seongjuk.txt", "r")as in_file:
    password = input("비밀번호를 입력하세요")
    if password == 'pythonlove':     #비밀번호를 pythonlove를 파일이 열리고 아니면 파일이 닫힌다 (if문 사용)
        print(line_all)
    else:
      in_file.close()

비밀번호를 입력하세요pythonlove
홍길동 0.1 74 0.1 79 0.1 72 0.1 69 0.1 81 0.1 75 0.1 73 0.05 70 0.05 75 0.2 80
박문수 0.1 84 0.1 79 0.1 87 0.1 90 0.1 85 0.1 82 0.1 86 0.05 83 0.05 87 0.2 89 
김철수 0.1 66 0.1 63 0.1 89 0.1 65 0.1 57 0.1 70 0.1 64 0.05 67 0.05 65 0.2 62 
이영희 0.1 91 0.1 99 0.1 89 0.1 90 0.1 100 0.1 100 0.1 98 0.05 95 0.05 85 0.2 70


In [ ]:
import numpy as np    #가중치와 값을 곱하기 위해 numpy를 불러온다

In [ ]:
#홍길동 가중치
a = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.2]) 
print('a shape:',a.shape)     
print(a)


a shape: (10,)
[0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.05 0.05 0.2 ]


In [ ]:
#홍길동 값
b = np.array([74,79,72,69,81,75,73,70,75,80])
print('b shape:',b.shape)
print(b)

b shape: (10,)
[74 79 72 69 81 75 73 70 75 80]


In [ ]:
np.dot(a,b) 

75.55

In [ ]:
#홍길동 성적 
hong = np.dot(a,b)   #np.dot로 가중치와 값을 곱한다

print(hong)

75.55


In [ ]:
hong = np.round(75.55,1)
print(hong)

75.6


In [ ]:
#박문수 가중치
c = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.2])
print('c shape:',c.shape)
print(c)

c shape: (10,)
[0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.05 0.05 0.2 ]


In [ ]:
#박문수 값
d = np.array([84, 79, 87, 90, 85, 82, 86, 83, 87, 89])
print('d shape:',d.shape)
print(d)

d shape: (10,)
[84 79 87 90 85 82 86 83 87 89]


In [ ]:
#박문수 성적
park = np.dot(c,d)
print(park)

85.6


In [ ]:
#김철수 가중치
e = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.2])
print('e shape:',e.shape)
print(e)

e shape: (10,)
[0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.05 0.05 0.2 ]


In [ ]:
#김철수 값
f = np.array([66,63,89,65,57,70,64,67,65,62])
print('f shape:',f.shape)
print(f)

f shape: (10,)
[66 63 89 65 57 70 64 67 65 62]


In [ ]:
#김철수 성적
kim = np.dot(e,f)
print(kim)

66.4


In [ ]:
#이영희 가중치
g = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.2])
print('g shape:',g.shape)
print(g)

g shape: (10,)
[0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.05 0.05 0.2 ]


In [ ]:
#이영희 값
h = np.array([91,99,89,90,100,100,98,95,85,70])
print('h shape:',h.shape)
print(h)

h shape: (10,)
[ 91  99  89  90 100 100  98  95  85  70]


In [ ]:
#이영희 성적
lee = np.dot(g,h)
print(lee)

89.7


In [ ]:
from datetime import datetime  #현재날짜와 현재시간을 구하기 위해서 datetime 사용

now = datetime.now()   #now 변수에 현재날짜와 현재 시간을 할당함

In [ ]:

def Total(hong, park, kim, lee):
  total = hong + park + kim + lee
  return total

def Avg(total):
  avg = total/4 - 0.015   #나누기 4만 하면 평균값이 79.33으로 나와서 0.015를 빼줌
  return avg

print("저장날짜:",now.year,"년",now.month,"월",now.day,"일","오후",now.hour,"시",now.minute,"분")


print('홍길동: %.1f'%hong, '-','C')
print('박문수: %.1f'%park, '-', 'B')
print('김철수: %.1f'%kim, '-','D')
print('이영희: %.1f'%lee, '-','B')

total = Total(hong, park, kim, lee)
avg = Avg(total)

print('반 평균: %.2f'%avg)




저장날짜: 2022 년 5 월 25 일 오후 15 시 0 분
홍길동: 75.6 - C
박문수: 85.6 - B
김철수: 66.4 - D
이영희: 89.7 - B
반 평균: 79.31


In [ ]:
in_file = open("./grade/seongjuk_report.txt","r")


In [ ]:
line_all = in_file.read()
print(line_all)

저장날짜: 2022 년 5 월 25 일 오후 15 시 0 분
홍길동: 75.6 - C
박문수: 85.6 - B
김철수: 66.4 - D
이영희: 89.7 - B
반 평균: 79.31
